spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      max-evictable-idle-time-millis: 3000000
      max-wait: 60000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ddu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
#  profiles:
#    active: uat
#TkMybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.fcf.daydayup.face.model